import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { generateStorageKey, validatePaperUpload } from './storage.service.js';
import { ValidationError } from '../lib/errors.js';

/**
 * Unlike storage.service.test.ts (hand-built buffers with just the PDF
 * magic bytes prepended), these tests load genuinely-generated PDF
 * files from disk - apps/api/test-fixtures/*.pdf were produced by
 * PyMuPDF (the same library apps/document-service uses for real
 * extraction), not synthesized in JS. This is what "test the entire
 * workflow using actual files" actually means for the parts of the
 * workflow that don't need a live Supabase project to exercise.
 */

const FIXTURES_DIR = join(import.meta.dirname, '..', '..', 'test-fixtures');

function loadFixture(name: string): Buffer {
  return readFileSync(join(FIXTURES_DIR, name));
}

describe('validatePaperUpload against real PDF files', () => {
  it('accepts a real, multi-question exam paper PDF generated by PyMuPDF', () => {
    const buffer = loadFixture('sample-exam-paper.pdf');
    const result = validatePaperUpload(buffer, 'application/pdf', 'sample-exam-paper.pdf');
    expect(result.sizeBytes).toBe(buffer.length);
    expect(result.checksumSha256).toMatch(/^[0-9a-f]{64}$/);
  });

  it('computes the exact same SHA-256 the OS sha256sum tool computes for the same file (duplicate detection depends on this matching what a real client/CDN/anything else would compute)', () => {
    const buffer = loadFixture('sample-exam-paper.pdf');
    const result = validatePaperUpload(buffer, 'application/pdf');
    // Computed independently via `sha256sum apps/api/test-fixtures/sample-exam-paper.pdf`
    expect(result.checksumSha256).toBe('e8b3fc0917e8de47e3181e121f3d2c70ee24ceeea11508e9ca015631b746129b');
  });

  it('gives two different real PDFs with different content different checksums', () => {
    const a = validatePaperUpload(loadFixture('sample-exam-paper.pdf'), 'application/pdf');
    const b = validatePaperUpload(loadFixture('sample-exam-paper-v2.pdf'), 'application/pdf');
    expect(a.checksumSha256).not.toBe(b.checksumSha256);
  });

  it('gives the exact same file loaded twice the same checksum, regardless of how many times it is re-validated (a resubmission of the identical file must be detected as a duplicate deterministically)', () => {
    const first = validatePaperUpload(loadFixture('sample-exam-paper.pdf'), 'application/pdf');
    const second = validatePaperUpload(loadFixture('sample-exam-paper.pdf'), 'application/pdf');
    expect(first.checksumSha256).toBe(second.checksumSha256);
  });

  it('rejects a real text file renamed to end in .pdf and declared as application/pdf (the magic-byte check catches what the extension/MIME checks alone would miss)', () => {
    const buffer = loadFixture('fake-not-a-pdf.pdf');
    expect(() => validatePaperUpload(buffer, 'application/pdf', 'fake-not-a-pdf.pdf')).toThrow(ValidationError);
  });

  it('generates a storage key for a real file that never collides across repeated uploads of the same content', () => {
    const buffer = loadFixture('sample-exam-paper.pdf');
    validatePaperUpload(buffer, 'application/pdf');
    const keyA = generateStorageKey('CSC101');
    const keyB = generateStorageKey('CSC101');
    expect(keyA).not.toBe(keyB);
  });
});
