-- Seed the programme catalogue used by public student registration.
-- The supplied School values are represented as faculties; programmes are grouped under a catalogue department for each faculty.

create temporary table njala_programme_catalogue (school text not null, name text not null);

insert into njala_programme_catalogue (school, name) values
    ('Education', 'Bachelor of Art in Development Communication'),
    ('Education', 'Bachelor of Art in Political Science'),
    ('Education', 'Bachelor of Arts in Education with Majors CRK'),
    ('Education', 'Bachelor of Arts in Education with Majors English'),
    ('Education', 'Bachelor of Arts in Education with Majors History'),
    ('Education', 'Bachelor of Arts in Education with Majors in French'),
    ('Education', 'Bachelor of Arts in Education with Majors in Linguistics'),
    ('Education', 'Bachelor of Arts in Education with Majors in Literature'),
    ('Education', 'Bachelor of Arts in Education with Majors Political Science'),
    ('Education', 'Bachelor of Education (Nursery and Pre-school Education)'),
    ('Education', 'Bachelor of Education (with various options)'),
    ('Education', 'Bachelor of Education Distance Learning'),
    ('Social Sciences & Law', 'Bachelor of Law (LLB)'),
    ('Natural Resources Management', 'Bachelor of Science (Honours) in Aquaculture and Fisheries Management'),
    ('Natural Resources Management', 'Bachelor of Science (honours) in Forestry'),
    ('Natural Resources Management', 'Bachelor of Science (Honours) in Horticulture'),
    ('Natural Resources Management', 'Bachelor of Science (Honours) in Wildlife Management and Conservation'),
    ('Natural Resources Management', 'Bachelor of Science (Honours) in Wood Science'),
    ('Social Sciences & Law', 'Bachelor of Science in Accounting'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Agribusiness Management'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Agricultural Communication and Media'),
    ('Social Sciences & Law', 'Bachelor of Science in Agricultural Economics'),
    ('Education', 'Bachelor of Science in Agricultural Education'),
    ('Technology', 'Bachelor of Science in Agricultural Engineering'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Agricultural Extension and Rural Sociology'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Agriculture General'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Animal Health and Production'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Animal Science'),
    ('Environmental Sciences', 'Bachelor of Science in Applied Ecology and Conservation'),
    ('Technology', 'Bachelor of Science in Applied Physics (Biophysics Option)'),
    ('Technology', 'Bachelor of Science in Applied Physics (with Bio Physics option)'),
    ('Social Sciences & Law', 'Bachelor of Science in Banking and Finance'),
    ('Environmental Sciences', 'Bachelor of Science in Biological Sciences'),
    ('Technology', 'Bachelor of Science in Business and Information Technology'),
    ('Environmental Sciences', 'Bachelor of Science in Chemistry'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Clothing & Textile (Hon)'),
    ('Community Health Sciences', 'Bachelor of Science in Community Health and Clinical Sciences'),
    ('Technology', 'Bachelor of Science in Computer Science'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Crop Protection'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Crop Science'),
    ('Environmental Sciences', 'Bachelor of Science in Development Studies'),
    ('Social Sciences & Law', 'Bachelor of Science in Economics'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Education with major Home Economics'),
    ('Education', 'Bachelor of Science in Education with major in Biology'),
    ('Education', 'Bachelor of Science in Education with Major in Health Education'),
    ('Education', 'Bachelor of Science in Education with Major in Human Kinetics'),
    ('Education', 'Bachelor of Science in Education with Major in Mathematics'),
    ('Education', 'Bachelor of Science in Education with Majors in Chemistry'),
    ('Education', 'Bachelor of Science in Education with Majors in Economics'),
    ('Education', 'Bachelor of Science in Education with Majors in Geography'),
    ('Education', 'Bachelor of Science in Education with Majors in Physics'),
    ('Technology', 'Bachelor of Science in Electronics and Telecommunication'),
    ('Technology', 'Bachelor of Science in Energy Studies'),
    ('Social Sciences & Law', 'Bachelor of Science in Entrepreneurship and Industrial Development'),
    ('Environmental Sciences', 'Bachelor of Science in Environment and Development'),
    ('Environmental Sciences', 'Bachelor of Science in Environmental Chemistry'),
    ('Environmental Sciences', 'Bachelor of Science in Environmental Management and Quality Control'),
    ('Environmental Sciences', 'Bachelor of Science in Environmental Physics'),
    ('Environmental Sciences', 'Bachelor of Science in Geography'),
    ('Education', 'Bachelor of Science in Home Economics Education'),
    ('Technology', 'Bachelor of Science in Industrial Technology'),
    ('Technology', 'Bachelor of Science in Mathematics'),
    ('Natural Resources Management', 'Bachelor of Science in Natural Resources Management (General)'),
    ('Social Sciences & Law', 'Bachelor of Science in Peace and Development Studies'),
    ('Environmental Sciences', 'Bachelor of Science in Physics'),
    ('Technology', 'Bachelor of Science in Physics with Computer Science'),
    ('Technology', 'Bachelor of Science in Physics with Telecommunication option'),
    ('Environmental Sciences', 'Bachelor of Science in Rural Development'),
    ('Environmental Sciences', 'Bachelor of Science in Rural Development Studies'),
    ('Social Sciences & Law', 'Bachelor of Science in Social Work'),
    ('Social Sciences & Law', 'Bachelor of Science in Sociology'),
    ('Agriculture and Food Sciences', 'Bachelor of Science in Soil Science'),
    ('Technology', 'Bachelor of Science in Statistics'),
    ('Agriculture and Food Sciences', 'Bachelor of Science with Honours in Agri-Business Management'),
    ('Agriculture and Food Sciences', 'Bachelor of Science with Honours in Food Nutrition Security'),
    ('Agriculture and Food Sciences', 'Bachelor of Science with Honours in Home Economics and Community Development'),
    ('Community Health Sciences', 'Bachelor of Science with Honours in Nursing'),
    ('Agriculture and Food Sciences', 'Bachelor of Science with Honours in Nutrition and Dietetics'),
    ('Community Health Sciences', 'Bachelor of Science with Honours in Public Health'),
    ('Social Sciences & Law', 'Bachelors of Science (Hons) Business Administration and Management'),
    ('Agriculture and Food Sciences', 'Certificate in Agriculture General'),
    ('Natural Resources Management', 'Certificate in Aquaculture and Fisheries Management'),
    ('Social Sciences & Law', 'Certificate in Business Administration'),
    ('Education', 'Certificate in Development Communications & Journalism'),
    ('Natural Resources Management', 'Certificate in Forestry'),
    ('Natural Resources Management', 'Certificate in Horticulture'),
    ('Natural Resources Management', 'Certificate in Wildlife Management and Conservation'),
    ('Natural Resources Management', 'Certificate in Wood Science'),
    ('Social Sciences & Law', 'Diploma in Banking and Finance'),
    ('Social Sciences & Law', 'Diploma in Business Administration and Management'),
    ('Community Health Sciences', 'Diploma in Community Health Assistant (CHA)'),
    ('Technology', 'Diploma in Computer Science and Information Technology'),
    ('Education', 'Diploma in Development Communications & Journalism'),
    ('Technology', 'Diploma in Electronics and Computer Technology'),
    ('Technology', 'Diploma in Industrial Technology'),
    ('Technology', 'Diploma in Statistics'),
    ('Agriculture and Food Sciences', 'Higher Diploma in Agriculture General (Agronomy Option)'),
    ('Agriculture and Food Sciences', 'Higher Diploma in Agriculture General (Forestry Option)'),
    ('Agriculture and Food Sciences', 'Higher Diploma in Agriculture General (Livestock Option)'),
    ('Natural Resources Management', 'Higher Diploma in Aquaculture and Fisheries Management'),
    ('Community Health Sciences', 'Higher Diploma in Community Health & Clinical Studies'),
    ('Technology', 'Higher Diploma in Computer Science and Information Technology'),
    ('Technology', 'Higher Diploma in Computer Systems Technology with Combined (Web and Mobile)'),
    ('Technology', 'Higher Diploma in Computer Systems Technology with Data Communications and Networking'),
    ('Technology', 'Higher Diploma in Computer Systems Technology with Database Design and Management'),
    ('Technology', 'Higher Diploma in Computer Systems Technology with Technical Programming'),
    ('Technology', 'Higher Diploma in Electronics and Computer Technology'),
    ('Community Health Sciences', 'Higher Diploma in Environmental Health Sciences (Public Health)'),
    ('Technology', 'Higher Diploma in Farm Mechanization'),
    ('Agriculture and Food Sciences', 'Higher Diploma in Food Technology & Nutrition'),
    ('Natural Resources Management', 'Higher Diploma in Forestry'),
    ('Natural Resources Management', 'Higher Diploma in Horticulture'),
    ('Technology', 'Higher Diploma in Industrial Technology'),
    ('Community Health Sciences', 'Higher Diploma in Ophthalmic for Community Health Officers (OCHO)'),
    ('Community Health Sciences', 'Higher Diploma in Pharmacies Dispensing Technology (DPDT)'),
    ('Social Sciences & Law', 'Higher Diploma in Social Work'),
    ('Community Health Sciences', 'Higher Diploma in State Registered Nurse (SRN)'),
    ('Technology', 'Higher Diploma in Statistics'),
    ('Natural Resources Management', 'Higher Diploma in Wildlife Management and Conservation'),
    ('Natural Resources Management', 'Higher Diploma in Wood Science'),
    ('Education', 'Higher Teachers Certificate (Primary)'),
    ('Education', 'Higher Teachers Certificate (Primary) Distance Learning'),
    ('Education', 'Higher Teachers Certificate (Secondary)'),
    ('Education', 'Higher Teachers Certificate (Secondary) Distance Learning'),
    ('Technology', 'M.Phil and PhD programmes'),
    ('Technology', 'M.Phil in Computer Science'),
    ('Social Sciences & Law', 'M.Phil in Finance'),
    ('Agriculture and Food Sciences', 'M.Phil. & PhD Programmes are also available'),
    ('Education', 'Master of Arts in Descriptive & Applied Linguistics'),
    ('Education', 'Master of Arts in Education - Literature'),
    ('Social Sciences & Law', 'Master of Arts in Peace and Development Studies'),
    ('Social Sciences & Law', 'Master of Business Administration (MBA) - Executive'),
    ('Social Sciences & Law', 'Master of Business Administration (MBA) - Finance'),
    ('Social Sciences & Law', 'Master of Business Administration (MBA) - Human Resources'),
    ('Social Sciences & Law', 'Master of Business Administration (MBA) - Marketing'),
    ('Social Sciences & Law', 'Master of Business Administration (MBA) - Project Management'),
    ('Education', 'Master of Education - Chemistry'),
    ('Education', 'Master of Education - Curriculum Development'),
    ('Education', 'Master of Education - Education Administration'),
    ('Education', 'Master of Education - Guidance and Counselling'),
    ('Education', 'Master of Education - Sports Administration and Management'),
    ('Education', 'Master of Education in Science Education'),
    ('Education', 'Master of Eduction - Measurement and Evaluation'),
    ('Natural Resources Management', 'Master of Philosophy in Aquaculture and Fisheries Management'),
    ('Natural Resources Management', 'Master of Philosophy in Forestry'),
    ('Natural Resources Management', 'Master of Philosophy in Horticulture'),
    ('Social Sciences & Law', 'Master of Public Administration'),
    ('Agriculture and Food Sciences', 'Master of Science in Agric. Extension & Rural sociology'),
    ('Social Sciences & Law', 'Master of Science in Agricultural Economics'),
    ('Education', 'Master of Science in Agriculture Education'),
    ('Agriculture and Food Sciences', 'Master of Science in Agronomy'),
    ('Agriculture and Food Sciences', 'Master of Science in Animal Science'),
    ('Natural Resources Management', 'Master of Science in Aquaculture and Fisheries Management'),
    ('Environmental Sciences', 'Master of Science in Biodiversity and Conservation'),
    ('Agriculture and Food Sciences', 'Master of Science in Clothing and Textiles'),
    ('Technology', 'Master of Science in Computer Science'),
    ('Agriculture and Food Sciences', 'Master of Science in Crop Protection'),
    ('Agriculture and Food Sciences', 'Master of Science in Crop Science'),
    ('Environmental Sciences', 'Master of Science in Development Studies'),
    ('Social Sciences & Law', 'Master of Science in Economics'),
    ('Education', 'Master of Science in Education - Biological and Measurement'),
    ('Education', 'Master of Science in Education - Geography'),
    ('Education', 'Master of Science in Education - Physics'),
    ('Education', 'Master of Science in Education - Physiology of Exercise'),
    ('Environmental Sciences', 'Master of Science in Environmental Chemistry'),
    ('Environmental Sciences', 'Master of Science in Environmental Management and Quality Control'),
    ('Technology', 'Master of Science in Exploration Geophysics'),
    ('Technology', 'Master of Science in Exploration Geophysics (Mineral and Groundwater Exploration)'),
    ('Natural Resources Management', 'Master of Science in Forestry'),
    ('Natural Resources Management', 'Master of Science in Horticulture'),
    ('Technology', 'Master of Science in Information Systems'),
    ('Natural Resources Management', 'Master of Science in Natural resources Management'),
    ('Agriculture and Food Sciences', 'Master of Science in Nutrition and Dietetics'),
    ('Technology', 'Master of Science in Post Harvest Technology'),
    ('Community Health Sciences', 'Master of Science in Public Health'),
    ('Technology', 'Master of Science in Renewable Energy and the Environment'),
    ('Environmental Sciences', 'Master of Science in Rural Development'),
    ('Social Sciences & Law', 'Master of Science in Sociology'),
    ('Technology', 'Master of Science in Soil & Water Engineering'),
    ('Agriculture and Food Sciences', 'Master of Science in Soil Science')
;

insert into faculties (name, code)
select distinct school, 'NJALA-SCHOOL-' || substr(md5(school), 1, 12)
from njala_programme_catalogue
on conflict (code) do nothing;

insert into departments (faculty_id, name, code)
select distinct f.id, 'Programmes', 'CATALOGUE'
from njala_programme_catalogue c
join faculties f on f.code = 'NJALA-SCHOOL-' || substr(md5(c.school), 1, 12)
on conflict (faculty_id, code) do nothing;

insert into programmes (department_id, name, code, level)
select distinct
  d.id,
  c.name,
  'CAT-' || substr(md5(c.school || '|' || c.name), 1, 12),
  case
    when c.name ilike '%phd%' then 'DOCTORAL'::programme_level
    when c.name ilike 'master%' or c.name ilike 'm.phil%' then 'MASTERS'::programme_level
    when c.name ilike 'higher diploma%' then 'POSTGRADUATE_DIPLOMA'::programme_level
    else 'UNDERGRADUATE'::programme_level
  end
from njala_programme_catalogue c
join faculties f on f.code = 'NJALA-SCHOOL-' || substr(md5(c.school), 1, 12)
join departments d on d.faculty_id = f.id and d.code = 'CATALOGUE'
on conflict (department_id, code) do nothing;

drop table njala_programme_catalogue;
